export const NETWORK = import.meta.env.VITE_APP_NETWORK ?? "testnet";
export const MODULE_ADDRESS = import.meta.env.VITE_MODULE_ADDRESS;
export const IS_DEV = Boolean(import.meta.env.DEV);
export const APTOS_API_KEY = import.meta.env.VITE_APTOS_API_KEY;

export const BettingCardDummy = [
  {
    game: "Kabaddi. India. Pro Kabaddi League",
    location: "Bengaluru, India",
    when: "TODAY, 20:00",
    teamA: "Patna Pirates",
    teamB: "Bengaluru Bulls",
    teamAImage: "https://via.placeholder.com/32",
    teamBImage: "https://via.placeholder.com/32",
    odds: [1.26, 17.0, 4.26],
  },
  {
    game: "Kabaddi. India. Pro Kabaddi League",
    location: "Bengaluru, India",
    when: "TODAY, 21:00",
    teamA: "Jaipur Pink Panthers",
    teamB: "Telugu Titans",
    teamAImage: "https://via.placeholder.com/32",
    teamBImage: "https://via.placeholder.com/32",
    odds: [1.7, 10.0, 5.0],
  },
  {
    game: "Football. UEFA Champions League",
    location: "London, England",
    when: "TOMORROW, 22:00",
    teamA: "Chelsea FC",
    teamB: "Real Madrid",
    teamAImage: "https://via.placeholder.com/32",
    teamBImage: "https://via.placeholder.com/32",
    odds: [2.5, 3.3, 2.8],
  },
  {
    game: "Basketball. NBA Finals",
    location: "Los Angeles, USA",
    when: "TOMORROW, 18:00",
    teamA: "Los Angeles Lakers",
    teamB: "Miami Heat",
    teamAImage: "https://via.placeholder.com/32",
    teamBImage: "https://via.placeholder.com/32",
    odds: [1.95, 4.5, 3.6],
  },
  {
    game: "Cricket. IPL",
    location: "Mumbai, India",
    when: "TOMORROW, 15:30",
    teamA: "Mumbai Indians",
    teamB: "Delhi Capitals",
    teamAImage: "https://via.placeholder.com/32",
    teamBImage: "https://via.placeholder.com/32",
    odds: [1.5, 2.2, 3.5],
  },
  {
    game: "Tennis. Wimbledon",
    location: "London, UK",
    when: "NEXT WEEK, 10:00",
    teamA: "Serena Williams",
    teamB: "Naomi Osaka",
    teamAImage: "https://via.placeholder.com/32",
    teamBImage: "https://via.placeholder.com/32",
    odds: [1.8, 3.5, 2.0],
  },
  {
    game: "Football. La Liga",
    location: "Madrid, Spain",
    when: "NEXT WEEK, 20:00",
    teamA: "Atletico Madrid",
    teamB: "Barcelona",
    teamAImage: "https://via.placeholder.com/32",
    teamBImage: "https://via.placeholder.com/32",
    odds: [2.4, 3.1, 2.5],
  },
  {
    game: "Basketball. NBA",
    location: "New York, USA",
    when: "NEXT WEEK, 21:00",
    teamA: "Brooklyn Nets",
    teamB: "Golden State Warriors",
    teamAImage: "https://via.placeholder.com/32",
    teamBImage: "https://via.placeholder.com/32",
    odds: [1.85, 4.0, 3.25],
  },
  {
    game: "Football. Premier League",
    location: "Manchester, England",
    when: "NEXT WEEK, 19:00",
    teamA: "Manchester United",
    teamB: "Liverpool FC",
    teamAImage: "https://via.placeholder.com/32",
    teamBImage: "https://via.placeholder.com/32",
    odds: [2.1, 3.4, 2.6],
  },
  {
    game: "Rugby. Six Nations Championship",
    location: "Paris, France",
    when: "NEXT WEEK, 16:30",
    teamA: "France",
    teamB: "England",
    teamAImage: "https://via.placeholder.com/32",
    teamBImage: "https://via.placeholder.com/32",
    odds: [1.95, 3.2, 4.1],
  },
  {
    game: "Tennis. Australian Open",
    location: "Melbourne, Australia",
    when: "NEXT MONTH, 14:00",
    teamA: "Roger Federer",
    teamB: "Novak Djokovic",
    teamAImage: "https://via.placeholder.com/32",
    teamBImage: "https://via.placeholder.com/32",
    odds: [1.5, 2.8, 3.2],
  },
  {
    game: "Cricket. ICC World Cup",
    location: "London, UK",
    when: "NEXT MONTH, 11:30",
    teamA: "England",
    teamB: "Australia",
    teamAImage: "https://via.placeholder.com/32",
    teamBImage: "https://via.placeholder.com/32",
    odds: [1.7, 3.6, 2.8],
  },
  {
    game: "Basketball. FIBA World Cup",
    location: "Beijing, China",
    when: "NEXT MONTH, 19:00",
    teamA: "USA",
    teamB: "Spain",
    teamAImage: "https://via.placeholder.com/32",
    teamBImage: "https://via.placeholder.com/32",
    odds: [1.5, 4.2, 3.0],
  },
  {
    game: "Football. Copa America",
    location: "Buenos Aires, Argentina",
    when: "NEXT MONTH, 22:00",
    teamA: "Brazil",
    teamB: "Argentina",
    teamAImage: "https://via.placeholder.com/32",
    teamBImage: "https://via.placeholder.com/32",
    odds: [2.1, 3.5, 2.2],
  },
  {
    game: "Baseball. MLB",
    location: "Chicago, USA",
    when: "NEXT MONTH, 17:00",
    teamA: "Chicago Cubs",
    teamB: "New York Yankees",
    teamAImage: "https://via.placeholder.com/32",
    teamBImage: "https://via.placeholder.com/32",
    odds: [1.85, 3.4, 2.9],
  },
];

export default BettingCardDummy;
