[package]
name = "prediction_market"

version = "1.0.0"
authors = ["Aditya & Raksha"]
[addresses]
prediction_market = "_"

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-framework/", rev = "main" }